import axios from 'axios';

const FAST2SMS_API_KEY = 'aW4IYGcD1SM7Fdxtfo3uzRJErP6KHZLl9QisCwONphv2TAm5XnFwXAdLNrzasBWoP6ic0Uhf8y3JZxEQ';
const PHONE_NUMBER_ID = '1208214062364694';
const API_URL = `https://www.fast2sms.com/dev/whatsapp/v24.0/${PHONE_NUMBER_ID}/messages`;

/**
 * Sends a real-time WhatsApp OTP using Fast2SMS WABA API
 * @param {string} mobileNo - 10-digit mobile number
 * @param {string} otp - The OTP generated by the server
 */
export const sendWhatsAppOtp = async (mobileNo, otp) => {
  // Normalize mobile number (remove any dial code, prefix with 91 for India)
  const cleanMobile = mobileNo.replace(/[^0-9]/g, '').slice(-10);
  const recipient = `91${cleanMobile}`;
  
  const trySend = async (templateName) => {
    console.log(`[OTP Service] Attempting to send WhatsApp OTP to ${recipient} using template "${templateName}"...`);
    const response = await axios.post(
      API_URL,
      {
        messaging_product: 'whatsapp',
        recipient_type: 'individual',
        to: recipient,
        type: 'template',
        template: {
          name: templateName,
          language: {
            code: 'en'
          },
          components: [
            {
              type: 'body',
              parameters: [
                {
                  type: 'text',
                  text: otp
                }
              ]
            }
          ]
        }
      },
      {
        headers: {
          'authorization': FAST2SMS_API_KEY,
          'Content-Type': 'application/json'
        }
      }
    );
    return response.data;
  };

  try {
    // 1. Try sending with the new dedicated account alert template
    const data = await trySend('sewvee_account_alert');
    console.log('[OTP Service] Sent successfully using primary template:', data);
    return data;
  } catch (error) {
    console.warn('[OTP Service] Failed with primary template. Error:', error.response?.data || error.message);
    
    // 2. Automatically fall back to the approved payment_completed template
    console.log('[OTP Service] Falling back to "payment_completed" template...');
    try {
      const data = await trySend('payment_completed');
      console.log('[OTP Service] Sent successfully using fallback template:', data);
      return data;
    } catch (fallbackError) {
      console.error('[OTP Service] Fallback template failed too:', fallbackError.response?.data || fallbackError.message);
      throw fallbackError;
    }
  }
};

